# service/manifests/workflows.yaml

flux_default:
  workflow_file: "flux_default.json"
  description: "Optimized Flux T2I with full API control."
  parameters:
    - prompt # Использует параметр "prompt" из base.yaml
    - seed
    - width
    - height
    - steps
    - lora
    - lora_strength
    - model
    - FBC_optimize

  # Здесь мы можем переопределить свойства для этого конкретного workflow
  overrides:
    prompt:
      required: true # Для этого workflow промпт обязателен

# Пример для будущего
# sdxl_upscale:
#  workflow_file: "sdxl_upscale.json"
#  description: "Upscales an image using SDXL."
#  parameters:
#    - input_image
#  overrides:
#    input_image:
#      required: true
